/**
 * src/lib/database.types.ts
 * Auto-generated by: npm run db:types
 * DO NOT edit manually.
 *
 * Regenerate after any schema change:
 *   cd mobile-app && npm run db:types
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Placeholder until first generation — replace with full output of:
// npx supabase gen types typescript \
//   --db-url postgresql://postgres:8xrpOeUbsnztzTBmU045cUOyyQTEzd2d@localhost:5433/postgres
export interface Database {
  public: {
    Tables:    Record<string, never>
    Views:     Record<string, never>
    Functions: Record<string, never>
    Enums:     Record<string, never>
  }
}
